name: Deploy Forum API to AWS EC2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/forum-api
  EC2_HOST: ${{ secrets.EC2_HOST }}
  EC2_USER: ${{ secrets.EC2_USER }}

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: forumapi_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run database migrations
      run: npm run migrate:test up
      env:
        PGHOST: localhost
        PGPORT: 5432
        PGDATABASE: forum_api_test
        PGUSER: postgres
        PGPASSWORD: password

    - name: Run tests
      run: npm test
      env:
        PGHOST: localhost
        PGPORT: 5432
        PGDATABASE: forum_api_test
        PGUSER: postgres
        PGPASSWORD: password
        ACCESS_TOKEN_KEY: test-access-token-key
        REFRESH_TOKEN_KEY: test-refresh-token-key
        ACCESS_TOKEN_AGE: 3000

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ env.DOCKER_IMAGE }}:latest
          ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          # Stop and remove existing containers
          docker-compose -f /home/${{ secrets.EC2_USER }}/forum-api/docker-compose.prod.yml down || true
          
          # Pull latest image
          docker pull ${{ env.DOCKER_IMAGE }}:latest
          
          # Update docker-compose file
          cd /home/${{ secrets.EC2_USER }}/forum-api
          
          # Start new containers
          docker-compose -f docker-compose.prod.yml up -d
          
          # Run migrations
          docker-compose -f docker-compose.prod.yml exec -T app npm run migrate
          
          # Clean up unused images
          docker image prune -f
